services:
  - type: web
    name: peres-ai-course
    env: node
    plan: free
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npm run start
    autoDeploy: true
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
